### ISSUE TITLE
Waffle Plate 3D-CAD data on OnShape

### ISSUE THREAD

**Issue by roboshiba** [ROBOTIS-GIT/turtlebot3#192]
TB3 3D-CAD datas that linked from e-manual are partially different from actual product.
Please update formal data of Waffle Plate.
It is necessary for optional camera mount and extended parts design by user own.
Thanks.

![sws0173](https://user-images.githubusercontent.com/5852451/39186232-b40bf064-4804-11e8-8c9f-f3593dedac74.JPG)

![sws0172](https://user-images.githubusercontent.com/5852451/39186150-7f5afa4a-4804-11e8-8fce-bbaa9f73d2e7.JPG)

**Comment by routiful** [comment]
Hi :)

3D printable data of Waffle plate is different to Off-the-shelf data of it. Because Off-the-shelf data isn't compatible with 3D printing. But data you commented has identical specification with formal data.
If someone wanted to design for extended parts, they could believe uploaded data on Onshape.

Thanks

**Comment by roboshiba** [comment]
I understood!
That's excellent reason.
If you can, PLS add this memo to e-manual.

Thanks.
