### ISSUE TITLE
Lidar imu limitation solution any

### ISSUE THREAD

**Issue by timlo94** [ROBOTIS-GIT/turtlebot3#218]
ISSUE TEMPLATE ver. 0.0.1

1. Which TurtleBot3 you have?

- [ ] burger
Burger
- [ ] waffle
- [ ] waffle pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

- [ ] Raspberry Pi 3
Rpi3 b
- [ ] Intel Joule
- [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

- [ ] Ubuntu MATE 16.04 or later
16.04
- [ ] Raspbian
- [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in RemotePC?

- [ ] Ubuntu 16.04 LTS (Xenial Xerus)
16.04
- [ ] Ubuntu 18.04 LTS (Bionic Beaver)
- [ ] Linux Mint 18.X
- [ ] etc (PLEASE, WRITE DOWN YOUR OS)

3. Write down software version and firmware version

 - Software version : [0.1.2]
Latest
 - Firmware version : [1.1.2]
 Latest
4. Write down the commands you used in order

 [RemotePC] roscore
 [SBC] roslaunch turtlebot3_bringup turtlebot3_robot.launch
 [RemotePC] roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch
 
5. Copy and Paste your error message on terminal

```
... logging to /home/darby/.ros/log/0681c5f0-5343-11e8-b6e2-ac2b6e6d08ee/roslaunch-kingod-25077.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.10.3:46024/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)

auto-starting new master
process[master]: started with pid [25087]
ROS_MASTER_URI=http://192.168.10.3:11311

setting /run_id to 0681c5f0-5343-11e8-b6e2-ac2b6e6d08ee
process[rosout-1]: started with pid [25100]
started core service [/rosout]
process[turtlebot3_core-2]: started with pid [25108]
[INFO] [1525840798.011640]: ROS Serial Python Node
[INFO] [1525840798.021582]: Connecting to /dev/ttyACM0 at 115200 baud
[ERROR] [1525840798.024494]: Error opening serial: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
[turtlebot3_core-2] process has finished cleanly
log file: /home/darby/.ros/log/0681c5f0-5343-11e8-b6e2-ac2b6e6d08ee/turtlebot3_core-2*.log
```
  
6. Please, describe detailedly what difficulty you are in 

- my lidar and imu sensor does not work in large environment, such as in industry with many machine and large open spaces. I would like other members developer to specify the limit of lds lidar and also imu sensor with maximum environment. And i would like to suggest developer to create a code which can follow side by side and run at constant velocity.

**Comment by kijongGil** [comment]
Hi timlo94 :)
First of all, maximum range of lds is 3.5m. and imu sensor works whether the environment is large or small. refer to our emanual : http://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_lds_01/#appendix-lds01

And then, your sensors do not work because the port is not connected. Check what do you use serial port Raspberry3 and OpenCR.  Default serial port is /dev/ttyACM0. 
If your serial port is connected, check your serial port by follow command.

`ls /dev/`

Thanks.

**Comment by kijongGil** [comment]
Hi timlo94 :)
First of all, maximum range of lds is 3.5m. and imu sensor works whether the environment is large or small. refer to our emanual : http://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_lds_01/#appendix-lds01

And then, your sensors do not work because the port is not connected. Check what do you use serial port Raspberry3 and OpenCR.  Default serial port is /dev/ttyACM0. 
If your serial port is connected, check your serial port by follow command.

`ls /dev/`

Thanks.

**Comment by timlo94** [comment]
Thanks ya...for my part, currently the SLAM draw incorrectly map with turtlebot3 icon jerking (jumping around the map).
 
I am figuring whether i should change the original lds lidar to RP LIDAR A3 would help in my industry field.

Right now, i replace the SLAM and NAVIGATION rviz with barcode scanner / line following to counter the situation.

**Comment by kijongGil** [comment]
Could tell me more about the SLAM draw incorrectly map??

**Comment by timlo94** [comment]
The map would be different from as usual.....it become round shape with no solid walls . 

Normally when we do slam, we would get square map cornered with thick solid wall.

**Comment by kijongGil** [comment]
could you show me your map?

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
