### ISSUE TITLE
Scan lines hitting the front camera on `waffle` turtlebot3 gazebo simulation

### ISSUE THREAD

**Issue by mturnshek** [ROBOTIS-GIT/turtlebot3#234]
There is an issue with the Gazebo simulation of `TURTLEBOT3_MODEL=waffle`, the one with both a single-channel lidar and a realsense camera. This only happens on `waffle` and not `waffle_pi` or `burger`.

Some of the lidar's scan lines are blocked the realsense camera attached to the front of the robot. This causes the navigation stack to sometimes act as if there is an obstacle directly in front of the robot. Navigation mostly still works, but this causes the `waffle` robot to occasionally back up for no apparent reason.

Here are a few images from rviz showing what's going on with the scan lines. Notice the red dots toward the front of the robot. This does not occur with `waffle_pi` or `burger`.

![rviz_lidar_blocked2](https://user-images.githubusercontent.com/867278/41173367-9a868ad0-6b24-11e8-9eb0-b4d05332a851.png)
![rviz_lidar_blocked](https://user-images.githubusercontent.com/867278/41173370-9bdec3e8-6b24-11e8-991e-5b913d2cef87.png)

Let me know if I can provide any additional data that's useful for this issue's resolution.

**Comment by routiful** [comment]
Hi :)

Thank you for sharing problem.
That problem is caused by collision pose of `[camera_link](https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_description/urdf/turtlebot3_waffle.urdf.xacro#L207)`. It is solved little adjust origin of it
For example,

```
<origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
```

However, I don't exactly know why it was happened. The origin of collision didn't overlapped with lidar sensor. I will ask why it is occurred to Gazebo forum.

Thanks

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
