### ISSUE TITLE
turtlebot3 using only DYNAMIXEL U2D2?!?!?

### ISSUE THREAD

**Issue by 3mrrrx** [ROBOTIS-GIT/turtlebot3#801]
would it be possible to control turtlebot3 using only DYNAMIXEL U2D2?

I am build my turtlebot3 for old parts, and using the U2D2 should be very doable in theory, but I can not find an implantation for this. In theory using U2D2 would be even better, as the OpenCR has to split its processor time between publishing, sensor reading and running the motors.

The OpenCR code apparently also calculates and sets some minor controls for the messages coming from the PI. so these have to be also handled within the controller node on the pi... please correct me if i am wrong here.

looking for an implementation in ROS2-Foxy or Galactic.

thankful on any help in this regard

**Comment by ashekim** [comment]
HI. @3mrrrx. Thanks for your interest in turtlebot3.
OpenCR has the ability to control DYNAMIXEL. And OpenCR has various sensors including IMU. 
The IMU sensor is used when calculating the odom of TB3. 

So unfortunately, it is difficult to control TurtleBot3 with only U2D2.
Sorry it wasn't the answer you were looking for.

thank you.

**Comment by 3mrrrx** [comment]
regarding the IMU and maybe the other sensor, these can be including in ROS separately and would published to the NAV or any other ROS node.

i also looked at the OpenCR code... it should be possible to implement the hole thing in python.. its quite a lot of work, but would also open a lot of possibilities.

**Comment by ashekim** [comment]
@3mrrrx 

Hi again.
If you check the link below, you can check the specifications of OpenCR.
- [OpenCR Spec](https://emanual.robotis.com/docs/en/parts/controller/opencr10/#specifications)

The OpeCR board contains various sensors including the IMU sensor.
If you only use U2D2, it means that you cannot get the IMU sensor value even if you modify the code.
Therefore, if you use U2D2 instead of OPENCR, you need a additional imu sensor.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity.
