### ISSUE TITLE
[ERROR] TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_left_link at time 18209.293000 according to authority unknown_publisher at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.6/src/buffer_core.cpp

### ISSUE THREAD

**Issue by Dhivyabharathi10** [ROBOTIS-GIT/turtlebot3#930]
Hi
I am getting the error while I am doing navigation topic in turtlebot3 burger using ROS noetic.
[ERROR] TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_left_link at time 18209.293000 according to authority unknown_publisher at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.6/src/buffer_core.cpp
Help me to solve this error.

**Comment by hanlinniu** [comment]
Hello, have you solved this problem? I have the same problem

**Comment by 98kje** [comment]
Hello I've solved this part, but it's not perfect.
This problem seems to be the same situation as me if this problem occurs
without any problems with the robot in the Gazebo simulation.
In my case, at the end of the paragraph when executing launch,
"2>>(grep-vTF_REPATED_DATA)
buffer_core)" This part was additionally entered to solve the problem
I hope my answer will be of great help to you. Thank you.

2023년 5월 6일 (토) 오전 7:00, hanlinniu ***@***.***>님이 작성:

**Comment by sandilyasg** [comment]
@98kje can you please share the full launch file with your method to solve the error?

**Comment by yun-goon** [comment]
Hi.
It is difficult to reproduce the issue with the provided information alone. For more accurate assistance, please follow the error report template with detailed descriptions.

A similar timestamp error may occur if you are using both Gazebo simulation and the actual robot at the same time, which can cause timestamp conflicts. If this is the case, please ensure to separate the simulation from the actual robot usage. 
Thank you.

**Comment by sunghowoo** [comment]
@Dhivyabharathi10  This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
