### ISSUE TITLE
Can't setup OpenCR in ROS2 Humble

### ISSUE THREAD

**Issue by Newmodel-YUKECHI** [ROBOTIS-GIT/turtlebot3#943]
- [ ] ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 2 Humble

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] ubuntu 22.04

4. Which OS you installed on SBC?

    - [ ] ubuntu 22.04

5. Which OS you installed on Remote PC?

    - [ ] ubuntu 22.04

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - launch# ros2 launch turtlebot3_bringup robot.launch.py

8. Copy and Paste the error messages on terminal.

[INFO] [launch]: All log files can be found below /root/.ros/log/2023-03-22-05-35-27-420981-yuki-Lenovo-IdeaPad-L340-15API-9001
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_waffle_pi.urdf
[INFO] [robot_state_publisher-1]: process started with pid [9007]
[INFO] [hlds_laser_publisher-2]: process started with pid [9009]
[INFO] [turtlebot3_ros-3]: process started with pid [9011]
[robot_state_publisher-1] [INFO] [1679463327.816807432] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-1] [INFO] [1679463327.820216057] [robot_state_publisher]: got segment base_link
[turtlebot3_ros-3] [INFO] [1679463327.820143279] [turtlebot3_node]: Init TurtleBot3 Node Main
[turtlebot3_ros-3] [INFO] [1679463327.820665647] [turtlebot3_node]: Init DynamixelSDKWrapper
[hlds_laser_publisher-2] [INFO] [1679463327.821195907] [hlds_laser_publisher]: Init hlds_laser_publisher Node Main
[hlds_laser_publisher-2] [INFO] [1679463327.821513211] [hlds_laser_publisher]: port : /dev/ttyUSB0 frame_id : base_scan
[robot_state_publisher-1] [INFO] [1679463327.824533919] [robot_state_publisher]: got segment base_scan
[robot_state_publisher-1] [INFO] [1679463327.824570727] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-1] [INFO] [1679463327.824595941] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-1] [INFO] [1679463327.824619827] [robot_state_publisher]: got segment camera_rgb_optical_frame
[robot_state_publisher-1] [INFO] [1679463327.824644692] [robot_state_publisher]: got segment caster_back_left_link
[robot_state_publisher-1] [INFO] [1679463327.824669976] [robot_state_publisher]: got segment caster_back_right_link
[robot_state_publisher-1] [INFO] [1679463327.824697564] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-1] [INFO] [1679463327.824722709] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-1] [INFO] [1679463327.824745059] [robot_state_publisher]: got segment wheel_right_link
[turtlebot3_ros-3] [INFO] [1679463327.825697459] [DynamixelSDKWrapper]: Succeeded to open the port(/dev/ttyACM0)!
[turtlebot3_ros-3] [INFO] [1679463327.839946941] [DynamixelSDKWrapper]: Succeeded to change the baudrate!
[turtlebot3_ros-3] [ERROR] [1679463327.874348608] [turtlebot3_node]: Failed connection with Devices
[turtlebot3_ros-3] [INFO] [1679463327.875894618] [turtlebot3_node]: Add Motors
[turtlebot3_ros-3] [INFO] [1679463327.876006648] [turtlebot3_node]: Add Wheels
[turtlebot3_ros-3] [INFO] [1679463327.876042409] [turtlebot3_node]: Add Sensors
[turtlebot3_ros-3] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[turtlebot3_ros-3]   what():  could not create publisher: rcl node's context is invalid, at ./src/rcl/node.c:428
[ERROR] [hlds_laser_publisher-2]: process has died [pid 9009, exit code 255, cmd '/opt/ros/humble/lib/hls_lfcd_lds_driver/hlds_laser_publisher --ros-args -r __node:=hlds_laser_publisher --params-file /tmp/launch_params__fbjdohz'].
[ERROR] [turtlebot3_ros-3]: process has died [pid 9011, exit code -6, cmd '/opt/ros/humble/lib/turtlebot3_node/turtlebot3_ros -i /dev/ttyACM0 --ros-args --params-file /opt/ros/humble/share/turtlebot3_bringup/param/waffle_pi.yaml'].

9. Please describe the issue in detail.

    - In line 25, [turtlebot3_node]: Failed connection with Devices
    - In line 31, [hlds_laser_publisher-2]: process has died [pid 9009, exit code 255, cmd '/opt/ros/humble/lib/hls_lfcd_lds_driver/hlds_laser_publisher --ros-args -r __node:=hlds_laser_publisher --params-file /tmp/launch_params__fbjdohz'].
    - In line 32, [turtlebot3_ros-3]: process has died [pid 9011, exit code -6, cmd '/opt/ros/humble/lib/turtlebot3_node/turtlebot3_ros -i /dev/ttyACM0 --ros-args --params-file /opt/ros/humble/share/turtlebot3_bringup/param/waffle_pi.yaml'].
    - we can't set up OpenCR cause of above errors.

**Comment by shiba-8ro** [comment]
In addition, Turtlebot3 Kit included LiDAR that sold in Japan from the second half of 2022 is LDS-02.

**Comment by bastinat0r** [comment]
I have the same issue. I have the old LDS and set the variable as follows:
`export LDS_MODEL=LDS1`. As far as I can tell, the laser scanner is not the issue, but the OpenCR board is behaving badly.
You can see how my turtlebots are set up with an ansible script from this repo: https://github.com/ovgu-FINken/driving_swarm_ansible

**Comment by bastinat0r** [comment]
Update: I connected the OpenCR board from another robot and the launch file works as expected, so the problem is in fact the OpenCR board. However, I do not know how to fix the problem. I already tried to update the firmware on the OpenCR, which did not help.

**Comment by abinayadinesh1** [comment]
@JeremyLebon I think I made the same mistake: I did both the RPI and the Arduino setup. How did you set up the openCr setup from scratch and try again?

**Comment by GyuH13** [comment]
Hi. @abinayadinesh1 
You should just follow index 0.3 in here https://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup
* follow manual for your version
below example for humble.
```
$ sudo dpkg --add-architecture armhf
$ sudo apt update
$ sudo apt install libc6:armhf

$ export OPENCR_PORT=/dev/ttyACM0
$ export OPENCR_MODEL=burger
$ rm -rf ./opencr_update.tar.bz2

$ wget https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS2/latest/opencr_update.tar.bz2
$ tar -xvf ./opencr_update.tar.bz2

$ cd ~/opencr_update
$ ./update.sh $OPENCR_PORT $OPENCR_MODEL.opencr
```
If you apply this command, normal setup source will be injected to opencr.

**Comment by sunghowoo** [comment]
This issue should be resolved by carefully following the manual setup instructions. I will proceed to close this issue for now. If the issue recurs, please feel free to submit it again.

**Comment by Massimo-Ita** [comment]
Hi Sunghowoo,

I just purchased a TurtleBot 3 burger, but haven't been able to make it work. I describe the issue in details following the suggested template:

1. Which TurtleBot3 platform do you use?

TurtleBot 3 Burger

2. Which ROS is working with TurtleBot 3?

ROS2 Humble

3. Which SBC is working on TurtleBot 3?

Raspberry Pi 4 with 4GB RAM

4. Which OS you installed on SBC?

Ubuntu Server 22.04.5 LTS (64-bit)

5. Which OS you installed on Remote PC?

Ubuntu 22.04 Desktop

6. Specify the software and firmware version (Can be found from Bringup messages)

fw_name: burger 
fw_ver: V230127R1 

I don't know where to find the software version, however I paste in the next section several screenshots including the Bringup messages.

7. Specify the commands or instructions to reproduce the issue.

SUMMARY OF THE ISSUE:

I followed the instructions carefully from the [OpenCR Setup chapter](https://docs.robotis.com/docs/systems/turtlebot3/quick_start_guide/opencr_setup) and everything goes well until I upload the firmware to the OpenCR. The firmware upload appears successful:

<img width="1075" height="509" alt="Image" src="https://github.com/user-attachments/assets/6d36e25c-298e-4794-9a0a-477a03822622" />

After the firmware update is complete, the board plays a short rising sequence of beeps, which I suppose indicates that it starts up. And then an endless beep-beep-beep begins, which I suppose indicates an error.

Following the instructions in the OpenCR Test section, I tried pressing SW1 and SW2 but the motors don't move. Consequently, as the instructions say, I followed section [Setup DYNAMIXELs for TurtleBot3](https://docs.robotis.com/docs/systems/turtlebot3/faq#setup-dynamixels-for-turtlebot3) to setup and test the motors. See the following screenshots:

SETUP LEFT

<img width="366" height="212" alt="Image" src="https://github.com/user-attachments/assets/75781203-2f75-4984-b87d-4757650386ee" />

TEST LEFT

<img width="295" height="119" alt="Image" src="https://github.com/user-attachments/assets/069fa611-eefb-44c6-9a10-21b7ba9c60e1" />

The test is successful and the left motor turns.

SETUP RIGHT

<img width="348" height="207" alt="Image" src="https://github.com/user-attachments/assets/c2a836b3-f21c-494e-aafa-67a1e3e3bea4" />

TEST RIGHT

<img width="302" height="119" alt="Image" src="https://github.com/user-attachments/assets/40804765-bf41-4241-b0e2-042727e8fec7" />

The test is successful and the right motor turns.

At this point I reconnected both motors and reflashed the firmware:

<img width="1070" height="533" alt="Image" src="https://github.com/user-attachments/assets/f11c5c7b-dd80-481f-840d-89ec5a612172" />

Unfortunately nothing changed. Still the same beep-beep-beep that goes on forever and the motors don't turn if I press SW1 or SW2. Rebooting the Turtlebot doesn't help either, it keeps going into the beep-beep-beep and motors don't turn.

Here are the error messages that appear if I launch the Bringup:

<img width="1417" height="804" alt="Image" src="https://github.com/user-attachments/assets/f4aa49c4-39bc-4e4f-84e9-30d4de440e9a" />

I don't know if the error relates to the motors, or maybe to the LIDAR as in the post at the beginning of this thread. With regard to the LIDAR, i followed exactly the instructions in SBC Setup and entered  echo 'export LDS_MODEL=LDS-03' >> ~/.bashrc

Are you able to say what the problem is? Is it software or hardware?

Thanks in advance for your help,
Massimo
